version: '3'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web
  web:
    build: .
    command: bash -c "
      python manage.py migrate &&
      echo
        \"from django.contrib.auth import get_user_model;
          User = get_user_model();
          User.objects.filter(email='admin@blog.com').delete();
          User.objects.create_superuser('admin', 'admin@blog.com', 'password')
        \" | python manage.py shell &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"